Repository S-KEEP/S-KEEP_Front, pull requests merged in 2024-09, with the labels that each got.

#51 [SKP-168-category-add] 카테고리 추가 및 삭제
  src/assets/icon/ic_card_etc.svg
  src/assets/icon/ic_delete.svg
  src/assets/icon/ic_empty.svg
  src/assets/icon/ic_noti.svg
  src/assets/icon/ic_noti_color.svg
  src/assets/icon/ic_plus.svg
  src/assets/icon/ic_round_activity.svg
  src/assets/icon/ic_round_etc.svg
  src/assets/icon/ic_round_festival.svg
  src/assets/icon/ic_round_food.svg
  src/assets/icon/ic_round_history.svg
  src/assets/icon/ic_round_nature.svg
  src/assets/icon/ic_round_rest.svg
  src/assets/icon/ic_round_shopping.svg
  src/assets/icon/index.ts
  src/components/Category/EmptyCategoryList.style.ts
  src/components/Category/EmptyCategoryList.tsx
  src/components/common/Category/CategoryCard/CategoryCard.style.tsx
  src/components/common/Header/CustomHeader.tsx
  src/constants/components/CategoryCard.ts
  src/hooks/mutations/category/useDeleteCategory.ts
  src/hooks/mutations/category/usePostCategoryAdd.ts
  src/hooks/queries/category/useGetCategoryDetail.ts
  src/hooks/queries/category/useGetCategoryList.ts
  src/navigators/StackNavigator.tsx
  src/navigators/constants/menu.ts
  src/navigators/types/index.ts
  src/screens/CategoryAdd/CategoryAdd.style.ts
  src/screens/CategoryAdd/CategoryAdd.tsx
  src/screens/CategoryList/CategoryList.style.ts
  src/screens/CategoryList/CategoryList.tsx
  src/screens/TabNavigator/CategoryTab/CategoryTab.style.ts
  src/screens/TabNavigator/CategoryTab/CategoryTab.tsx
  src/types/components/category/category.ts
Labels: feat💡

#50 [SKP-171-analyze-result-extra] 명소 상세 추가 정보
  App.tsx
  ios/skeepcli/Info.plist
  src/apis/client.ts
  src/assets/icon/ic_airplane.svg
  src/assets/icon/ic_check.svg
  src/assets/icon/ic_clear.svg
  src/assets/icon/ic_cloudy.svg
  src/assets/icon/ic_partly_cloudy.svg
  src/assets/icon/ic_rain.svg
  src/assets/icon/ic_rain_and_snow.svg
  src/assets/icon/ic_shower.svg
  src/assets/icon/ic_snow.svg
  src/assets/icon/ic_trash.svg
  src/assets/icon/ic_warn.svg
  src/assets/icon/index.ts
  src/components/common/BottomSheet/CategoryBottomSheet/CategoryBottomSheet.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Global/Snackbar/Snackbar.tsx
  src/components/common/Global/Toast/Toast.tsx
  src/components/common/Tourism/SkeletonTourismItem.tsx
  src/components/common/Tourism/Tourism.tsx
  src/components/common/Tourism/TourismItem.tsx
  src/components/common/Weather/Weather.tsx
  src/components/common/Weather/WeatherCard/SkeletonWeatherCard.tsx
  src/components/common/Weather/WeatherCard/WeatherCard.tsx
  src/components/common/Weather/WeatherSection/WeatherSection.tsx
  src/constants/components/WeatherCards.ts
  src/hooks/mutations/location/useDeleteLocation.ts
  src/hooks/mutations/location/usePostTourLocation.ts
  src/hooks/queries/QueryKeys.ts
  src/hooks/queries/category/useGetCategoryDetail.ts
  src/hooks/queries/location/useGetLocation.ts
  src/hooks/queries/tourism/useGetTourList.ts
  src/hooks/queries/weather/useGetWeather.ts
  src/hooks/useAnalyze.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/constants/menu.ts
  src/navigators/types/index.ts
  src/screens/Analyze/Analyze.tsx
  src/screens/AnalyzeResult/AnalyzeResult.tsx
  src/screens/Detail/Detail.tsx
  src/screens/DetailTour/DetailTour.styles.ts
  src/screens/DetailTour/DetailTour.tsx
  src/types/dtos/tourLocation.ts
  src/types/dtos/weather.ts
Labels: feat💡

#54 [SKP-169-sights-to-travel] 명소 -> 여행지 워딩 변경
  src/apis/client.ts
  src/hooks/mutations/category/useDeleteCategory.ts
  src/hooks/mutations/location/useDeleteLocation.ts
  src/hooks/mutations/location/usePatchLocation.ts
  src/hooks/mutations/location/usePatchLocationReAnalyze.ts
  src/hooks/mutations/location/usePostLocation.ts
  src/hooks/mutations/location/usePostTourLocation.ts
  src/hooks/queries/location/useGetLocation.ts
  src/screens/AnalyzeResult/AnalyzeResult.tsx
  src/screens/DetailTour/DetailTour.tsx
  src/screens/Login/Login.tsx
  src/screens/Withdraw/Withdraw.tsx
Labels: fix 🐞

#55 [SKP-179-fix-category] 카테고리 추가 버튼 비활성화 처리
  src/screens/CategoryAdd/CategoryAdd.tsx
Labels: feat💡

#56 [SKP-180] 카테고리 추가 버튼 위치 고정
  .husky/prepare-commit-msg
  src/components/common/Header/CustomHeader.tsx
  src/components/common/Icon/Icon.tsx
  src/navigators/StackNavigator.tsx
  src/screens/AnalyzeResult/AnalyzeResult.tsx
  src/screens/CategoryList/CategoryList.tsx
  src/screens/Detail/Detail.tsx
  src/screens/DetailTour/DetailTour.styles.ts
  src/screens/DetailTour/DetailTour.tsx
  src/screens/Withdraw/Withdraw.tsx
Labels: fix 🐞

#61 [SKP-184-UI-notification] 알림 화면 퍼블리싱
  ios/skeepcli.xcodeproj/project.pbxproj
  src/assets/icon/ic_bell.svg
  src/assets/icon/index.ts
  src/components/Notification/NotificationItem.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/constants/menu.ts
  src/navigators/types/index.ts
  src/screens/Notification/Notification.styles.ts
  src/screens/Notification/Notification.tsx
  src/screens/Notification/dummies.json
  src/screens/TabNavigator/SettingTab/SettingTab.style.ts
  src/screens/TabNavigator/SettingTab/SettingTab.tsx
  src/styles/typography.ts
Labels: feat💡

#68 [SKP-191-qa-UI] UI 요청사항 반영
  src/assets/icon/ic_card_etc_blue.svg
  src/assets/icon/ic_card_festival.svg
  src/assets/icon/ic_card_food.svg
  src/assets/icon/ic_card_history.svg
  src/assets/icon/ic_card_nature.svg
  src/assets/icon/ic_card_rest.svg
  src/assets/icon/ic_card_shopping.svg
  src/assets/icon/ic_empty.svg
  src/assets/icon/ic_folder.svg
  src/assets/icon/ic_marker.svg
  src/assets/icon/ic_round_activity.svg
  src/assets/icon/ic_round_etc.svg
  src/assets/icon/ic_round_festival.svg
  src/assets/icon/ic_round_food.svg
  src/assets/icon/ic_round_history.svg
  src/assets/icon/ic_round_nature.svg
  src/assets/icon/ic_round_rest.svg
  src/assets/icon/ic_round_shopping.svg
  src/assets/icon/index.ts
  src/components/Category/Icon/IcCategoryRound.tsx
  src/components/Detail/PlaceDetail/PlaceDetail.style.ts
  src/components/Detail/PlaceDetail/PlaceDetail.tsx
  src/components/ResultSwiper/ResultItem/ResultItem.style.ts
  src/components/Settings/Profile.tsx
  src/components/Settings/SettingList.tsx
  src/components/common/Category/CategoryCard/CategoryCard.style.tsx
  src/constants/components/CategoryCard.ts
  src/screens/CategoryList/CategoryList.style.ts
  src/screens/CategoryList/CategoryList.tsx
  src/screens/Detail/Detail.tsx
  src/screens/DetailTour/DetailTour.tsx
  src/screens/TabNavigator/CategoryTab/CategoryTab.style.ts
Labels: fix 🐞

#70 [SKP-192] UI 리젝사항 QA
  ios/skeepcli.xcodeproj/project.pbxproj
  ios/skeepcli/Info.plist
  src/screens/TabNavigator/CategoryTab/CategoryTab.style.ts
  src/screens/TabNavigator/CategoryTab/CategoryTab.tsx
  src/screens/TabNavigator/SettingTab/SettingTab.style.ts
  src/screens/TabNavigator/SettingTab/SettingTab.tsx
  src/screens/Withdraw/Withdraw.style.ts
  src/screens/Withdraw/Withdraw.tsx
Labels: fix 🐞

#73 [SKP-194-friend-category-add] 친구 명소 내 카테고리 추가 및 테스트 계정
  src/components/common/Tourism/EditorPickTourismItem.tsx
  src/components/common/Tourism/TourismItem.tsx
  src/hooks/mutations/category/useEditorCategoryAdd.ts
  src/hooks/mutations/friend/useFriendAdd.ts
  src/hooks/mutations/friend/usePostFriendLocationAdd.ts
  src/hooks/mutations/test/usePostTestLogin.ts
  src/hooks/queries/QueryKeys.ts
  src/hooks/queries/tourism/useGetEditorPickTourList.ts
  src/hooks/queries/tourism/useGetTourList.ts
  src/hooks/useAppleLogin.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/constants/menu.ts
  src/navigators/types/index.ts
  src/screens/EditorDetail/EditorDetail.style.ts
  src/screens/EditorDetail/EditorDetail.tsx
  src/screens/FriendDetail/FriendDetail.style.ts
  src/screens/FriendDetail/FriendDetail.tsx
  src/screens/Login/Login.tsx
  src/screens/TabNavigator/SettingTab/SettingTab.style.ts
  src/screens/TabNavigator/SettingTab/SettingTab.tsx
  src/types/dtos/tourLocation.ts
Labels: feat💡, todo ✅
