Repository S-KEEP/S-KEEP_Front, pull requests merged in 2024-07, with the labels that each got.

#2 [초기세팅] 폴더구조, eslint, 절대경로 설정
  .eslintrc.js
  babel.config.js
  ios/Podfile.lock
  package.json
  src/apis/.keep
  src/assets/.keep
  src/components/.keep
  src/constants/.keep
  src/container/AppSetupContainer.tsx
  src/hooks/mutations/index.ts
  src/hooks/queries/index.ts
  src/libs/react-query/index.tsx
  src/navigators/Navigator.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/TabNavigator.tsx
  src/navigators/constants/index.ts
  src/navigators/hooks/index.ts
  src/navigators/hooks/useNavigator.ts
  src/navigators/types/index.ts
  src/screens/Home.tsx
  src/styles/.keep
  src/types/.keep
  src/utils/.keep
  tsconfig.json
  yarn.lock
Labels: init ⚒️

#6 [초기세팅] Github-Jira 연동
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/ISSUE_TEMPLATE/🐞-bug-report-template.md
  .github/ISSUE_TEMPLATE/💡-feature-template.md
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: chore 🧹

#8 [SKP-42] Husky 세팅
  .github/pull_request_template.md
  .husky/prepare-commit-msg
  README.md
  package-lock.json
  package.json
  yarn.lock
Labels: chore 🧹

#11 [SKP-71] 라우팅 세팅
  App.tsx
  babel.config.js
  declarations.d.ts
  ios/Podfile.lock
  metro.config.js
  package.json
  src/assets/icon/user-blocked.svg
  src/assets/svg/Wser.tsx
  src/navigators/Navigator.tsx
  src/navigators/StackNavigator.tsx
  tsconfig.json
  yarn.lock
Labels: init ⚒️

#13 [SKP-97] TestFlight 업로드 세팅
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/pull_request_template.md
  ios/Podfile.lock
  ios/skeepcli.xcodeproj/project.pbxproj
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/1024.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/114.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/120.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/180.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/29.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/40.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/57.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/58.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/60.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/80.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/87.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/skeepcli/Info.plist
Labels: chore 🧹

#15 [SKP-73] 상세 화면 UI
  App.tsx
  android/app/src/main/assets/fonts/Pretendard-Black.ttf
  android/app/src/main/assets/fonts/Pretendard-Bold.ttf
  android/app/src/main/assets/fonts/Pretendard-ExtraBold.ttf
  android/app/src/main/assets/fonts/Pretendard-ExtraLight.ttf
  android/app/src/main/assets/fonts/Pretendard-Light.ttf
  android/app/src/main/assets/fonts/Pretendard-Medium.ttf
  android/app/src/main/assets/fonts/Pretendard-Regular.ttf
  android/app/src/main/assets/fonts/Pretendard-SemiBold.ttf
  android/app/src/main/assets/fonts/Pretendard-Thin.ttf
  android/link-assets-manifest.json
  babel.config.js
  ios/Podfile
  ios/Podfile.lock
  ios/link-assets-manifest.json
  ios/skeepcli.xcodeproj/project.pbxproj
  ios/skeepcli/AppDelegate.mm
  ios/skeepcli/Info.plist
  package-lock.json
  package.json
  react-native.config.js
  src/assets/fonts/Pretendard-Black.ttf
  src/assets/fonts/Pretendard-Bold.ttf
  src/assets/fonts/Pretendard-ExtraBold.ttf
  src/assets/fonts/Pretendard-ExtraLight.ttf
  src/assets/fonts/Pretendard-Light.ttf
  src/assets/fonts/Pretendard-Medium.ttf
  src/assets/fonts/Pretendard-Regular.ttf
  src/assets/fonts/Pretendard-SemiBold.ttf
  src/assets/fonts/Pretendard-Thin.ttf
  src/assets/icon/ic_cancel.svg
  src/assets/icon/ic_down.svg
  src/assets/icon/ic_folder.svg
  src/assets/icon/ic_left.svg
  src/assets/icon/ic_marker.svg
  src/assets/icon/ic_pagination_left.svg
  src/assets/icon/ic_pagination_right.svg
  src/assets/icon/ic_pin.png
  src/assets/icon/ic_rotate.svg
  src/assets/icon/ic_target.svg
  src/assets/icon/index.ts
  src/components/Detail/Map.tsx
  src/components/ResultSwiper/ResultItem/ResultItem.style.ts
  src/components/ResultSwiper/ResultItem/ResultItem.tsx
  src/components/ResultSwiper/ResultSwiper/ResultSwiper.tsx
  src/components/common/Button/Button.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/TabNavigator.tsx
  src/navigators/constants/menu.ts
  src/navigators/types/index.ts
  src/screens/Analyze/Analyze.tsx
  src/screens/AnalyzeResult/AnalyzeResult.styles.ts
  src/screens/AnalyzeResult/AnalyzeResult.tsx
  src/screens/AnalyzeResult/dummies.json
  src/screens/Detail/Detail.tsx
  src/screens/Home.tsx
  src/styles/common.ts
  src/styles/palette.ts
  src/styles/typography.ts
  yarn.lock
Labels: feat💡, todo ✅

#17 [SKP-73] 지도 라이브러리 오류 수정
  babel.config.js
  ios/Podfile
  ios/Podfile.lock
  ios/skeepcli.xcodeproj/project.pbxproj
  ios/skeepcli/AppDelegate.mm
  ios/skeepcli/Info.plist
  package.json
  src/assets/icon/ic_pin.png
  src/components/Detail/Map.tsx
  yarn.lock
Labels: fix 🐞
