Repository S-KEEP/S-KEEP_Front, pull requests merged in 2024-08, with the labels that each got.

#21 [SKP-11-image] 이미지 첨부
  App.tsx
  ios/Podfile
  ios/Podfile.lock
  ios/share/Base.lproj/MainInterface.storyboard
  ios/share/Info.plist
  ios/share/share-Bridging-Header.h
  ios/share/shareDebug.entitlements
  ios/skeepcli.xcodeproj/project.pbxproj
  ios/skeepcli.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/skeepcli/AppDelegate.mm
  ios/skeepcli/Info.plist
  ios/skeepcli/skeepcliDebug.entitlements
  package-lock.json
  package.json
  src/hooks/useShareExtension.tsx
  src/screens/Home.tsx
  yarn.lock
Labels: feat💡

#27 [SKP-111] 이미지 첨부
  App.tsx
  ios/Podfile
  ios/Podfile.lock
  ios/share/Base.lproj/MainInterface.storyboard
  ios/share/Info.plist
  ios/share/share-Bridging-Header.h
  ios/share/shareDebug.entitlements
  ios/skeepcli.xcodeproj/project.pbxproj
  ios/skeepcli/AppDelegate.mm
  ios/skeepcli/Info.plist
  ios/skeepcli/skeepcliDebug.entitlements
  package-lock.json
  package.json
  src/apis/authApi.ts
  src/apis/client.ts
  src/apis/queryClient.ts
  src/assets/icon/ic_festival.svg
  src/assets/icon/ic_history.svg
  src/assets/icon/ic_shopping.svg
  src/assets/icon/index.ts
  src/components/Detail/Map/Map.tsx
  src/components/Detail/PlaceDetail/PlaceDetail.style.ts
  src/components/Detail/PlaceDetail/PlaceDetail.tsx
  src/components/ResultSwiper/ResultItem/ResultItem.style.ts
  src/components/ResultSwiper/ResultItem/ResultItem.tsx
  src/components/ResultSwiper/ResultSwiper/ResultSwiper.tsx
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/BottomSheet/CategoryBottomSheet/CategoryBottomSheet.styles.ts
  src/components/common/BottomSheet/CategoryBottomSheet/CategoryBottomSheet.tsx
  src/components/common/BottomSheet/CategorySelector.tsx
  src/components/common/Button/ModifyButton.tsx
  src/components/common/Category/CategoryCard/.keep
  src/components/common/Category/CategoryItem/CategoryItem.tsx
  src/constants/components/CategoryCard.ts
  src/hooks/mutations/location/useDeleteLocation.ts
  src/hooks/mutations/location/usePatchLocation.ts
  src/hooks/mutations/location/usePostLocation.ts
  src/hooks/queries/QueryKeys.ts
  src/hooks/queries/category/useGetCategoryList.ts
  src/hooks/queries/location/useGetLocation.ts
  src/hooks/useShareExtension.tsx
  src/libs/react-query/index.tsx
  src/navigators/Navigator.tsx
  src/navigators/TabNavigator.tsx
  src/navigators/constants/label.ts
  src/navigators/types/index.ts
  src/screens/Analyze/Analyze.tsx
  src/screens/AnalyzeResult/AnalyzeResult.tsx
  src/screens/Detail/Detail.tsx
  src/screens/Home.tsx
  src/screens/MoreSettings/MoreSetteingScreen.tsx
  src/styles/palette.ts
  src/styles/types/index.ts
  src/styles/typography.ts
  src/types/dtos/location.ts
  yarn.lock
Labels: feat💡

#30 [SKP-141-image api] 이미지 분석, 수정 API 연결
  ios/skeepcli.xcodeproj/project.pbxproj
  src/assets/icon/ic_loading.gif
  src/components/Detail/PlaceDetail/PlaceDetail.tsx
  src/components/ResultSwiper/ResultItem/ResultItem.tsx
  src/components/ResultSwiper/ResultSwiper/ResultSwiper.tsx
  src/components/common/Category/CategoryItem/CategoryItem.tsx
  src/constants/states/AnalyzeState.ts
  src/hooks/mutations/location/usePatchLocation.ts
  src/hooks/mutations/location/usePatchLocationReAnalyze.ts
  src/hooks/mutations/location/usePostLocation.ts
  src/navigators/StackNavigator.tsx
  src/navigators/constants/menu.ts
  src/navigators/types/index.ts
  src/screens/Analyze/Analyze.styles.ts
  src/screens/Analyze/Analyze.tsx
  src/screens/AnalyzeError/AnalyzeError.styles.ts
  src/screens/AnalyzeError/AnalyzeError.tsx
  src/screens/AnalyzeResult/AnalyzeResult.tsx
  src/screens/Detail/Detail.tsx
  src/screens/MoreSettings/MoreSetteingScreen.tsx
  src/screens/ReAnalyze/ReAnalyze.styles.ts
  src/screens/ReAnalyze/ReAnalyze.tsx
  src/types/dtos/location.ts
Labels: feat💡

#31 [SKP-143-apple-login-reissue] 애플로그인 수정 및 탈퇴
  ios/Podfile.lock
  package.json
  src/apis/authApi.ts
  src/apis/client.ts
  src/assets/icon/ic_apple.svg
  src/assets/icon/ic_profile.svg
  src/assets/icon/ic_right.svg
  src/assets/icon/ic_warning.svg
  src/assets/icon/index.ts
  src/components/Login/AppleLogin.tsx
  src/components/Settings/Profile.style.ts
  src/components/Settings/Profile.tsx
  src/components/Settings/Setting.style.ts
  src/components/Settings/SettingItem.tsx
  src/components/Settings/SettingList.tsx
  src/components/common/Category/CategoryCard/CategoryCard.style.tsx
  src/components/common/Category/CategoryCard/CategoryCard.tsx
  src/components/common/PlaceDetail/PlaceDetail.style.ts
  src/components/common/PlaceDetail/PlaceDetail.tsx
  src/constants/components/CategoryCard.ts
  src/constants/queryKeys/userInfto.ts
  src/hooks/mutations/deleteAccount/useDeleteAppleId.ts
  src/hooks/mutations/deleteAccount/usePostDeleteAccount.ts
  src/hooks/queries/category/useGetCategoryList.ts
  src/hooks/queries/settings/useGetUserInfo.ts
  src/libs/recoil/constants/keys.ts
  src/libs/recoil/states/userAppleInfo.ts
  src/libs/recoil/type/userInfo.ts
  src/navigators/Navigator.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/TabNavigator.tsx
  src/navigators/constants/menu.ts
  src/navigators/types/index.ts
  src/screens/Category/CategoryScreen.style.ts
  src/screens/Category/CategoryScreen.tsx
  src/screens/CategoryList/CategoryListScreen.style.ts
  src/screens/CategoryList/CategoryListScreen.tsx
  src/screens/DeleteAccount/DeleteAccountScreen.style.ts
  src/screens/DeleteAccount/DeleteAccountScreen.tsx
  src/screens/Settings/SettingScreen.style.ts
  src/screens/Settings/SettingScreen.tsx
  src/types/dtos/auth.ts
  src/types/dtos/userInfo.ts
  yarn.lock
Labels: feat💡, fix 🐞

#35 [SKP-147-image-api2] 공유하기 > 이미지 분석
  App.tsx
  ios/share/Info.plist
  ios/skeepcli.xcodeproj/project.pbxproj
  ios/skeepcli/skeepcli.entitlements
  src/hooks/useAnalyze.tsx
  src/hooks/useShareExtension.tsx
  src/navigators/TabNavigator.tsx
  src/screens/AnalyzeError/AnalyzeError.tsx
Labels: feat💡

#36 [SKP-145-category-infinite-scroll] 카테고리 무한 스크롤
  src/assets/icon/ic_category_rest2.svg
  src/assets/icon/index.ts
  src/hooks/queries/category/useGetCategoryDetail.ts
  src/screens/CategoryList/CategoryListScreen.style.ts
  src/screens/CategoryList/CategoryListScreen.tsx
  src/types/dtos/category.ts
Labels: feat💡

#37 [SKP-146-logo] 로고 수정 및 screen 리팩토링
  ios/skeepcli.xcodeproj/project.pbxproj
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/1024.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/114.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/120.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/180.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/29.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/40.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/57.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/58.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/60.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/80.png
  ios/skeepcli/Images.xcassets/AppIcon.appiconset/87.png
  src/components/Settings/SettingList.tsx
  src/navigators/Navigator.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/TabNavigator.tsx
  src/navigators/constants/label.ts
  src/navigators/constants/menu.ts
  src/navigators/types/index.ts
  src/screens/CategoryList/CategoryList.style.ts
  src/screens/CategoryList/CategoryList.tsx
  src/screens/EtcTab.tsx
  src/screens/FriendTab.tsx
  src/screens/Login/Login.style.ts
  src/screens/Login/Login.tsx
  src/screens/MapTab.tsx
  src/screens/MoreSettings/MoreSetteingScreen.tsx
  src/screens/TabNavigator/CategoryTab/CategoryTab.style.ts
  src/screens/TabNavigator/CategoryTab/CategoryTab.tsx
  src/screens/TabNavigator/HomeTab/HomeTab.tsx
  src/screens/TabNavigator/SettingTab/SettingScreen.tsx
  src/screens/TabNavigator/SettingTab/SettingTab.style.ts
  src/screens/Withdraw/Withdraw.style.ts
  src/screens/Withdraw/Withdraw.tsx
Labels: chore 🧹, refactor ⚙️

#39 [Hotfix/share-extension] 공유하기 익스텐션 이슈 해결
  ios/Podfile.lock
  ios/share/share.entitlements
  ios/skeepcli.xcodeproj/project.pbxproj
  package.json
  src/components/Settings/SettingList.tsx
  src/navigators/TabNavigator.tsx
  src/navigators/constants/label.ts
  src/screens/TabNavigator/SettingTab/SettingTab.tsx
  yarn.lock
Labels: feat💡, fix 🐞

#41 [SKP-148-category-withdraw-refactor] 카테고리 상세 연결과 탈퇴 팝업창 추가
  src/assets/icon/ic_sad_face.svg
  src/assets/icon/index.ts
  src/components/Settings/SettingList.tsx
  src/components/common/BottomSheet/CategoryBottomSheet/CategoryBottomSheet.tsx
  src/components/common/Category/CategoryItem/CategoryItem.tsx
  src/components/common/Modal/Modal.style.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/PlaceDetail/PlaceDetail.style.ts
  src/components/common/PlaceDetail/PlaceDetail.tsx
  src/constants/components/CategoryCard.ts
  src/hooks/mutations/location/usePatchLocation.ts
  src/hooks/queries/QueryKeys.ts
  src/hooks/queries/category/useGetCategoryDetail.ts
  src/hooks/queries/category/useGetCategoryList.ts
  src/screens/AnalyzeResult/AnalyzeResult.tsx
  src/screens/CategoryList/CategoryList.style.ts
  src/screens/CategoryList/CategoryList.tsx
  src/screens/Detail/Detail.tsx
  src/screens/TabNavigator/SettingTab/SettingTab.tsx
  src/screens/Withdraw/Withdraw.style.ts
  src/screens/Withdraw/Withdraw.tsx
  src/styles/typography.ts
  src/types/dtos/category.ts
  src/types/dtos/location.ts
Labels: feat💡

#42 [SKP-155-fix-style] 1차 QA 로그인, 카테고리, 탭 반영
  src/assets/icon/ic_analyze.svg
  src/assets/icon/ic_apple_logo.svg
  src/assets/icon/index.ts
  src/components/Login/AppleLogin.style.ts
  src/components/Login/AppleLogin.tsx
  src/hooks/queries/category/useGetCategoryDetail.ts
  src/navigators/TabNavigator.tsx
  src/screens/CategoryList/CategoryList.tsx
  src/types/dtos/category.ts
Labels: fix 🐞

#40 [SKP-153-fix-analyze] 분석 QA
  App.tsx
  ios/Podfile.lock
  ios/skeepcli/AppDelegate.mm
  ios/skeepcli/Images.xcassets/Contents.json
  ios/skeepcli/Images.xcassets/Splash.imageset/Contents.json
  ios/skeepcli/Images.xcassets/Splash.imageset/splash.png
  ios/skeepcli/Images.xcassets/Splash.imageset/splash_2x.png
  ios/skeepcli/Images.xcassets/Splash.imageset/splash_3x.png
  ios/skeepcli/LaunchScreen.storyboard
  package.json
  src/assets/icon/ic_fail.png
  src/components/common/Button/Button.tsx
  src/components/common/Button/ModifyButton.tsx
  src/components/common/Category/CategoryItem/CategoryItem.tsx
  src/navigators/Navigator.tsx
  src/navigators/TabNavigator.tsx
  src/screens/AnalyzeError/AnalyzeError.tsx
  src/screens/AnalyzeResult/AnalyzeResult.tsx
  src/styles/palette.ts
  src/styles/types/index.ts
  yarn.lock
Labels: fix 🐞

#43 [SKP-152-fix-withdraw] apple Id 삭제 및 모달창 스타일
  src/components/common/Modal/Modal.style.ts
  src/hooks/queries/settings/useGetUserInfo.ts
  src/hooks/useAppleLogin.tsx
  src/screens/Withdraw/Withdraw.style.ts
  src/screens/Withdraw/Withdraw.tsx
Labels: fix 🐞

#44 [SKP-163-fix-detail] 상세 화면 로딩, 오류 처리
  ios/skeepcli.xcodeproj/project.pbxproj
  src/components/ErrorView/ErrorView.styles.ts
  src/components/ErrorView/ErrorView.tsx
  src/components/common/Category/CategoryItem/SkeletonCategoryItem.tsx
  src/components/common/PlaceDetail/PlaceDetail.style.ts
  src/components/common/PlaceDetail/SkeletonPlaceDetail.tsx
  src/components/common/Skeleton/Skeleton.tsx
  src/screens/AnalyzeError/AnalyzeError.tsx
  src/screens/Detail/Detail.tsx
Labels: feat💡

#46 [SKP-165-fix-token-reissue] 토큰 만료 로직 최종 수정
  ios/skeepcli.xcodeproj/project.pbxproj
  src/apis/client.ts
  src/navigators/Navigator.tsx
  src/screens/Login/Login.style.ts
  src/types/token.ts
Labels: fix 🐞

#47 [SKP-165-fix-typo-api] url 오타 수정
  src/hooks/queries/category/useGetCategoryList.ts
Labels: fix 🐞
